// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManagementSystem.Models;

public partial class tb_clientes
{
    [Key]
    public int cli_id_cliente { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string cli_nome { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string cli_cpf { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string cli_email { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cli_telefone { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cli_rua { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cli_bairro { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cli_cidade { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cli_estado { get; set; }

    public DateTime cli_data_criacao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cli_numero_casa { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cli_cep { get; set; }

    public byte[] cli_foto_cliente { get; set; }
}