// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManagementSystem.Models;

public partial class tb_fornecedores
{
    [Key]
    public int for_id_fornecedor { get; set; }

    public byte[] for_imagem { get; set; }

    public DateTime for_data_criacao { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string for_nome_fantasia { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string for_razao_social { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string for_email { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string for_telefone { get; set; }

    [StringLength(10)]
    public string for_cnpj { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string for_inscricao_estadual { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string for_inscricao_municipal { get; set; }

    [InverseProperty("pro_fk_id_fornecedoresNavigation")]
    public virtual ICollection<tb_produtos> tb_produtos { get; set; } = new List<tb_produtos>();
}