// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ManagementSystem.Models;

public partial class tb_produtos
{
    [Key]
    public int pro_id_produto { get; set; }

    public byte[] pro_imagem { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string pro_nome { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string pro_descricao { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal pro_preco { get; set; }

    public int pro_quantidade_estoque { get; set; }

    public DateTime pro_data_criacao { get; set; }

    public int pro_fk_id_fornecedores { get; set; }

    [ForeignKey("pro_fk_id_fornecedores")]
    [InverseProperty("tb_produtos")]
    public virtual tb_fornecedores pro_fk_id_fornecedoresNavigation { get; set; }
}