// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ManagementSystem.Models;
using Microsoft.EntityFrameworkCore;

namespace ManagementSystem.Context;

public partial class ManagementSystemContext : DbContext
{
    public ManagementSystemContext()
    {
    }

    public ManagementSystemContext(DbContextOptions<ManagementSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tb_clientes> tb_clientes { get; set; }

    public virtual DbSet<tb_fornecedores> tb_fornecedores { get; set; }

    public virtual DbSet<tb_produtos> tb_produtos { get; set; }

    public virtual DbSet<tb_usuario> tb_usuario { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=RAFAEL\\SQLEXPRESS;Initial Catalog=ManagementSystem;User ID=sa;Password=9173rafa; TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tb_fornecedores>(entity =>
        {
            entity.Property(e => e.for_cnpj).IsFixedLength();
        });

        modelBuilder.Entity<tb_produtos>(entity =>
        {
            entity.HasOne(d => d.pro_fk_id_fornecedoresNavigation).WithMany(p => p.tb_produtos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tb_produtos_tb_fornecedores");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}