//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using Microsoft.Extensions.Configuration;
using ManagementSystem.XPO.ManagementSystem;
namespace ManagementSystem.XPO.ManagementSystem
{
	public partial class ManagementSystemUnitOfWork : UnitOfWork
	{
		public ManagementSystemUnitOfWork() : base() { }
		public ManagementSystemUnitOfWork(DevExpress.Xpo.Metadata.XPDictionary dictionary) : base(dictionary) { }
		public ManagementSystemUnitOfWork(IDataLayer layer, params IDisposable[] disposeOnDisconnect) : base(layer, disposeOnDisconnect) { }
		public ManagementSystemUnitOfWork(IObjectLayer layer, params IDisposable[] disposeOnDisconnect) : base(layer, disposeOnDisconnect) { }
	}
}
namespace Microsoft.Extensions.DependencyInjection
{
	public static class ManagementSystemXpoServiceCollectionExtensions
	{
		public static IServiceCollection AddManagementSystemAsXpoDefaultUnitOfWork(this IServiceCollection serviceCollection, bool useDataLayerAsSingletone = true, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoDefaultUnitOfWork(useDataLayerAsSingletone, optionsBuilder);
		}
		public static IServiceCollection AddManagementSystemAsXpoDefaultSession(this IServiceCollection serviceCollection, bool useDataLayerAsSingletone = true, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoDefaultSession(useDataLayerAsSingletone, optionsBuilder);
		}
		public static IServiceCollection AddManagementSystemUnitOfWork(this IServiceCollection serviceCollection, bool useDataLayerAsSingletone = true, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoCustomSession<ManagementSystemUnitOfWork>(useDataLayerAsSingletone, optionsBuilder);
		}
		public static IServiceCollection AddManagementSystemXpoDefaultDataLayer(this IServiceCollection serviceCollection, ServiceLifetime lifetime, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoDefaultDataLayer(lifetime, customDataLayerOptionsBuilder);
		}
		public static IServiceCollection AddManagementSystemAsXpoDefaultUnitOfWork(this IServiceCollection serviceCollection, IConfiguration configuration, bool useDataLayerAsSingletone = true, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoDefaultUnitOfWork(useDataLayerAsSingletone, o => { o.UseConnectionStringForManagementSystem(configuration); optionsBuilder(o); });
		}
		public static IServiceCollection AddManagementSystemAsXpoDefaultSession(this IServiceCollection serviceCollection, IConfiguration configuration, bool useDataLayerAsSingletone = true, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoDefaultSession(useDataLayerAsSingletone, o => { o.UseConnectionStringForManagementSystem(configuration); optionsBuilder(o); });
		}
		public static IServiceCollection AddManagementSystemUnitOfWork(this IServiceCollection serviceCollection, IConfiguration configuration, bool useDataLayerAsSingletone = true, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoCustomSession<ManagementSystemUnitOfWork>(useDataLayerAsSingletone, o => { o.UseConnectionStringForManagementSystem(configuration); optionsBuilder(o); });
		}
		public static IServiceCollection AddManagementSystemXpoDefaultDataLayer(this IServiceCollection serviceCollection, IConfiguration configuration, ServiceLifetime lifetime, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoDefaultDataLayer(lifetime, o => { o.UseConnectionStringForManagementSystem(configuration); optionsBuilder(o); });
		}
		public static DataLayerOptionsBuilder UseConnectionStringForManagementSystem(this DataLayerOptionsBuilder options, IConfiguration configuration)
		{
			return options.UseConnectionString(configuration.GetConnectionString(ConnectionHelper.ConnectionStringName));
		}
		static Action<DataLayerOptionsBuilder> CreateDataLayerOptionsBuilder(Action<DataLayerOptionsBuilder> injectCustomDataLayerOptionsBuilder)
		{
			return (options) =>
			{
				options
				.UseEntityTypes(ConnectionHelper.GetPersistentTypes());
				if (injectCustomDataLayerOptionsBuilder != null)
				{
					injectCustomDataLayerOptionsBuilder(options);
				}
			};
		}
	}
}
