//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManagementSystem.XPO.ManagementSystem
{

	[Persistent(@"tb_usuario")]
	public partial class tb_usuarioXPO : XPLiteObject
	{
		int fusu_id_usuario;
		[Key(true)]
		public int usu_id_usuario
		{
			get { return fusu_id_usuario; }
			set { SetPropertyValue<int>(nameof(usu_id_usuario), ref fusu_id_usuario, value); }
		}
		string fusu_login;
		[Size(50)]
		public string usu_login
		{
			get { return fusu_login; }
			set { SetPropertyValue<string>(nameof(usu_login), ref fusu_login, value); }
		}
		string fusu_senha;
		[Size(50)]
		public string usu_senha
		{
			get { return fusu_senha; }
			set { SetPropertyValue<string>(nameof(usu_senha), ref fusu_senha, value); }
		}
		DateTime fusu_data_criacao;
		public DateTime usu_data_criacao
		{
			get { return fusu_data_criacao; }
			set { SetPropertyValue<DateTime>(nameof(usu_data_criacao), ref fusu_data_criacao, value); }
		}
		DateTime fusu_ultimo_login;
		public DateTime usu_ultimo_login
		{
			get { return fusu_ultimo_login; }
			set { SetPropertyValue<DateTime>(nameof(usu_ultimo_login), ref fusu_ultimo_login, value); }
		}
		bool fusu_status;
		public bool usu_status
		{
			get { return fusu_status; }
			set { SetPropertyValue<bool>(nameof(usu_status), ref fusu_status, value); }
		}
		string fusu_cargo;
		[Size(50)]
		public string usu_cargo
		{
			get { return fusu_cargo; }
			set { SetPropertyValue<string>(nameof(usu_cargo), ref fusu_cargo, value); }
		}
		DateTime fusu_bloqueado_ate;
		public DateTime usu_bloqueado_ate
		{
			get { return fusu_bloqueado_ate; }
			set { SetPropertyValue<DateTime>(nameof(usu_bloqueado_ate), ref fusu_bloqueado_ate, value); }
		}
		bool fusu_bloqueado;
		public bool usu_bloqueado
		{
			get { return fusu_bloqueado; }
			set { SetPropertyValue<bool>(nameof(usu_bloqueado), ref fusu_bloqueado, value); }
		}
		byte[] fusu_imagem_perfil;
		[Size(SizeAttribute.Unlimited)]
		[MemberDesignTimeVisibility(true)]
		public byte[] usu_imagem_perfil
		{
			get { return fusu_imagem_perfil; }
			set { SetPropertyValue<byte[]>(nameof(usu_imagem_perfil), ref fusu_imagem_perfil, value); }
		}
	}

}
